### ISSUE TITLE
Add & Format Deb's Academic Publications

### ISSUE THREAD

**Issue by sgadgets** [social-machines/social-machines.github.io#15]
**Two steps:**
1. Get all Deb's academic papers onto the site
2. Format in a particular way, details below

**Content Check**
We can reference here for all of his publications he'd like included on the site: 
https://scholar.google.com/citations?hl=en&user=btoec6QAAAAJ&view_op=list_works&sortby=pubdate

**Papers to Add**
These papers need to be added:
- [x] 10×—human-machine symbiosis
- [x] A System that Learns to Describe Objects in Visual Scenes
- [x] A computational model of three facets of meaning
- [x] A computational model of word learning from multimodal sensory input
- [x] A phoneme probability display for individuals with hearing disabilities
- [x] A visual context-aware multimodal system for spoken language processing
- [x] Affective learning—a manifesto
- [x] An Interface for Visualization and Exploration of Spatial Distributions
- [x] Automatic spoken affect classification and analysis
- [x] BISHOP| BLENDER: Spatially Grounded Language Understanding in 3D Modelling Software
- [x] Behavior Compilation for AI in Games
- [x] Beyond Linear Syntax: An Image-Oriented Communication Aid
- [x] Capturing and generating social behavior with the restaurant game
- [x] Computer assisted analysis of hand radiographs in infantile hypophosphatasia carriers
- [x] Connecting Language to Robot Behaviour: An Architecture of Object Schemas
- [x] Connecting language to the world
- [x] Context-Aware Multimodal System For Spoken Language Processing
- [x] Coupling Perception and Simulation: Steps Towards Conversational Robotics
- [x] Coupling Robot Perception and Online Simulation for Grounding Conversational Semantics
- [x] Coupling perception and simulation: Steps towards conversational robotics
- [x] Cross media targeted message synchronization
- [x] DeepSpace: Mood-Based Image Texture Generation for Virtual Reality from Music
- [x] Displaying estimated social interest in time-based media
- [x] Effects of Category Labels on Induction and Visual Processing: Support or Interference?
- [x] Estimating social interest in time-based media
- [x] Exploiting feature dynamics for active object recognition
- [x] Generalized grounding graphs: A probabilistic framework for understanding grounded language
- [x] Generating Audience Response Metrics and Ratings from Social Interest In Time-Based Media
- [x] Grounded situation models: Where words and percepts meet
- [x] Grounded speech communication
- [x] Grounding language in the world: Schema theory meets semiotics
- [x] Grounding language in the world: signs, schemas, and meaning
- [x] Grounding natural spoken language semantics in visual perception and motor control
- [x] Grounding verbs of motion in natural language commands to robots
- [x] Integration of a large text and audio corpus using speaker identification
- [x] Learning audio-visual associations using mutual information
- [x] Learning from Observing Tutoring Collaboratively
- [x] Learning influence among interacting Markov chains
- [x] Learning visually grounded words and syntax for a scene description task
- [x] Learning words from natural audio-visual input
- [x] Life in the network: the coming age of computational social science
- [x] Measuring Responsiveness in the Online Public Sphere for the 2016 US Election: Concepts
- [x] Multimodal adaptive interfaces
- [x] NewsComm: a hand-held interface for interactive access to structured audio
- [x] On Grounding the Content of Language
- [x] Perceptual intelligence: learning gestures and words for individualized, adaptive interfaces
- [x] Representing Intentions in a Cognitive Model of Language Acquisition: Effects of Phrase Structure on Situated Verb Learning
- [x] Ripley, Hand Me The Cup!(Sensorimotor representations for grounding word meaning)
- [x] Robots, language, and meaning
- [x] Rumor Gauge: Predicting the Veracity of Rumors on Twitter
- [x] See and Tell
- [x] Semi-automatic speech transcription
- [x] Situation-aware spoken language processing
- [x] Speaker identification based text to audio alignment for an audio retrieval system
- [x] Speaker indexing using neural network clustering of vowel spectra
- [x] SpeechBlocks: A Constructionist Early Literacy App
- [x] Star Graphs: Discretization, visualization, and analysis of tracking data
- [x] Teachable interfaces for individuals with dysarthric speech and severe physical disabilities
- [x] The ADS-to-IDS continuum: Developing an index for the study of infant directed speech prosody
- [x] The ITALK project: Integration and transfer of action and language knowledge in robots
- [x] Toco the toucan: a synthetic character guided by perception, emotion, and story
- [x] Topic and time based media affinity estimation
- [x] Toward an interleaved model of actions and words in social simulation
- [x] Towards visually-grounded spoken language acquisition
- [x] Twitter Demographic Classification Using Deep Multi-modal Multi-task Learning
- [x] Understanding complex visually referring utterances
- [x] Using acoustic structure in a hand-held audio playback device
- [x] Using synchronous speech to minimize variability
- [x] Visual context driven semantic priming of speech recognition and understanding
- [x] Wearable audio computing: A survey of interaction techniques
- [x] Word learning in a multimodal environment

**Examples of Format**
Below are some of Deb's academic publications in the MIT-compliant format he wants:

Papers in Refereed Journals
 
1. Michael Fleischman and Deb Roy. (in review). Intentions in Language Acquisition. Submitted to Cognitive Science. 31 pages.

2. Dong Zhang, Daniel Gatica-Perez, Samy Bengio, and Deb Roy. (in review). The Team-Player Influence Model. Submitted to Pattern Analysis and Machine Intelligence (PAMI). 26 pages.

3. Michael Levit and Deb Roy. (in revision). Understanding and Interpretation of Natural Language Navigational Instructions. Submitted to IEEE Systems, Man, and Cybernetics, Part B, 11 pages.

4. Peter Gorniak and Deb Roy. (in revision). Situated Language Understanding as Filtering Perceived Affordances. Submitted to Cognitive Science. 56 pages.

5. Deb Roy. (2005). Grounding Language in Perception and Action: Computational Insights. Trends in Cognitive Sciences, 9(8): 389-96.

6. Deb Roy and Ehud Reiter. (2005). Connecting Language to the World. Artificial Intelligence, 167(1-2): 1-12.

7. Deb Roy. (2005). Semiotic Schemas: A Framework for Grounding Language in the Action and Perception. Artificial Intelligence, 167(1-2): 170-205.

8. Deb Roy and Niloy Mukherjee. (2005). Visual Context Driven Semantic Priming of Speech Recognition and Understanding. Computer Speech and Language., 19(2): 227-248.

9. Rupal Patel, Sam Pilato, and Deb Roy. (2004). Beyond Linear Syntax: An Image-Oriented Communication Aid. Journal of Assistive Technology Outcomes and Benefits, 1(1): 57-66

10. Deb Roy, Kai-Yuh Hsiao, and Nikolaos Mavridis. (2004). Mental Imagery for a Conversational Robot. IEEE Transactions on Systems, Man, and Cybernetics, Part B, 34(3): 1374-1383.

11. Deb Roy. (2004). 10x: Human-machine Symbiosis. BT Technology Journal, 22(4): 121-124.

12. Peter Gorniak and Deb Roy. (2004). Grounded Semantic Composition for Visual Scenes, Journal of Artificial Intelligence Research, 21: 429-470.

13. Deb Roy. (2003). Grounded Spoken Language Acquisition: Experiments in Word Learning. IEEE Transactions on Multimedia, 34(3): 1374-1383.

14. Deb Roy. (2002). Learning Words and Syntax for a Visual Description Task. Computer Speech and Language, 16(3): 353-385.

15. Deb Roy and Alex Pentland. (2002). Learning Words from Sights and Sounds: A Computational Model. Cognitive Science, 26(1): 113-146.

16. Deb Roy. (2001). Learning Visually Grounded Words and Syntax of Natural Spoken Language. Evolution of Communication. 4(1): 33-56.

17. Deb Roy. (1997). Speaker indexing using neural network clustering of vowel spectra. International Journal of Speech Technology, 1(2): 143-149.

18. Chris Schmandt and Deb Roy. (1996). Using acoustic structure in a hand-held audio playback device. IBM Systems Journal, 35: (3-4).

19. B.N.Chodirker, D.Roy, C.R.Greenberg, M.Cheang, J.A.Evans, and M.H.Reed. (1991). Computer assisted analysis of hand radiographs in infantile hypophosphatasia carriers, Pediatric Radiology 21: 216-219.

 Papers in Refereed Conference Proceedings: 
 
20. Deb Roy, Rupal Patel, Philip DeCamp, Rony Kubat, Michael Fleischman, Brandon Roy, Nikolaos Mavridis, Stefanie Tellex, Alexia Salata, Jethran Guinness, Michael Levit, Peter Gorniak. (2006). The Human Speechome Project. Twenty-eighth Annual Meeting of the Cognitive Science Society, 6 pages.

21. Nikolaos Mavridis and Deb Roy. (2006). Grounded Situation Models for Robots: Where Words and Percepts Meet. IEEE/RSJ International Conference on Intelligent Robots and Systems (IROS).

22. Peter Gorniak and Deb Roy. The Affordance-Based Concept. (2006). Twenty-eighth Annual Meeting of the Cognitive Science Society, 6 pages.

23. Dong Zhang, Daniel Gatica-Perez, Deb Roy, and Samy Bengio. (2006). Modeling interactions from email communication. Int. Conf. on Multimedia & Expo (ICME), 4 pages.

24. Stefanie Tellex and Deb Roy. (2006). Spatial Routines for Understanding Context-Dependent Verbal Commands to a Mobile Robot. Proc. Int. Conf. of Human-Robot Interaction (HRI2006), 8 pages.

25. Michael Fleischman and Deb Roy. (2005). Why are verbs harder to learner than nouns? Initial insights from a computational model of situated word learning. 27th Annual Meeting of the Cognitive Science Society, 6 pages.

26. Philip DeCamp, Amber Frid-Jimenez, Jethran Guinness and Deb Roy (2005). Gist Icons: Seeing Meaning in Large Bodies of Literature. IEEE Information Visualization 2005 Conference, 2 pages.

27. Dong Zhang, Daniel Gatica-Perez, Samy Bengio, and Deb Roy. (2005). Learning Influence among Interacting Markov Chains. Neural Information Processing Systems (NIPS), 8 pages.

28. Peter Gorniak and Deb Roy (2005). Probabilistic Grounding of Situated Speech using Plan Recognition and Reference Resolution. Seventh International Conference on Multimodal Interfaces (ICMI), 6 pages. Best Paper Award.

29. Michael Fleischman and Deb Roy (2005). Intentional Context in Situated Language Learning. Proc. Ninth Conference on Computational Natural Language Learning, 8 pages.

30. Peter Gorniak and Deb Roy (2005). Speaking with your Sidekick: Understanding Situated Speech in Computer Role Playing Games. Proc. Artificial Intelligence and Interactive Digital Entertainment, 2005, 6 pages.

31. Joshua Juster and Deb Roy. (2004). Elvis: Situated Speech and Gesture Understanding for a Robotic Chandelier. Proc. Int. Conf. Multimodal Interfaces, 7 pages.

32. Deb Roy, Yair Ghitza, Jeff Bartelma, and Charlie Kehoe. (2004). Visual Memory Augmentation: Using Eye Gaze as an Attention Filter. Proc. IEEE International Symposium on Wearable Computers, 4 pages.

33. Kai-yuh Hsiao, Nikolaos Mavridis, Deb Roy. (2003). Coupling Perception and Simulation: Steps Towards Conversational Robotics. Proc. International Conference on Intelligent Robots and Systems, 6 pages.

34. Niloy Mukherjee and Deb Roy. (2003). A Visual Context-Aware Multimodal System for Spoken Language Processing. Proc. Eurospeech, 6 pages.

35. Peter Gorniak and Deb Roy. (2003). Augmenting Interfaces with Adaptive Speech Commands. Proc. International Conference on Multimodal Interfaces, 4 pages.

36. Peter Gorniak and Deb Roy. (2003). A Visually Grounded Natural Language Interface for Reference to Spatial Scenes. Proc. International Conference on Multimodal Interfaces, 8 pages.

37. Deb Roy, Peter Gorniak, Niloy Mukherjee, and Josh Juster. (2002). A Trainable Spoken Language Understanding System for Visual Object Selection. Proceedings of the International Conference of Spoken Language Processing, 4 pages.

38. Deb Roy. (2002). A Trainable Visually-Grounded Spoken Language Generation System. Proceedings of the International Conference of Spoken Language Processing, 4 pages.

39. Ewa Dominowska, Deb Roy and Rupal Patel. (2002). An Adaptive Context-Sensitive Communication Aid. Proceedings of CSUN International Conference on Technology and Persons with Disabilities.
 
40. Deb Roy. (2000). Grounded Speech Communication. Proceedings of the International Conference on Spoken Language Processing, 5 pages.

41. Deb Roy. (2000). Learning from multimodal observations. Proceedings of the IEEE International Conference Multimedia and Expo (ICME), New York, NY., 4 pages.

42. Deb Roy. (2000). Integration of Speech and Vision using Mutual Information. Proceedings of the IEEE International Conference on Acoustics, Speech and Signal Processing, 4 pages.

43. Deb Roy. (2000). A computational model of word learning from multimodal sensory input. Proceedings of the International Conference of Cognitive Modeling, 8 pages.

44. Rupal Patel and Deb Roy. (1999). Adaptive spoken communication aids. Proceedings of the Conference of the American Speech and Hearing Association, San Francisco, CA.

45. Deb Roy and Alex Pentland. (1998). Learning Words from Audio-Visual Input. Proceedings of the International Conference on Spoken Language Processing, 5 pages.

46. Deb Roy and Alex Pentland. (1998). Word Learning in a Multimodal Environment, Proceedings of the IEEE International Conference on Acoustics, Speech and Signal Processing, 4 pages.

47. Deb Roy and Alex Pentland. (1998). A Phoneme Probability Display for Individuals with Hearing Disabilities. Proceedings of the ACM Conference On Assistive Technologies, 4 pages.

48. Deb Roy and Carl Malamud. (1997). Speaker identification based test to audio alignment for an audio retrieval system. Proceedings of the IEEE International Conference on Acoustics, Speech and Signal Processing, Munich, Vol. 2, pp. 1099-1103.

49. Deb Roy and Alex Pentland. (1996).Automatic Spoken Affect Analysis and Classification. Proceedings of the International Conference on Automatic Face and Gesture Recognition, 6 pages.

50. Deb Roy and Chris Schmandt. (1996). NewsComm: A Hand-Held Interface for Interactive Access to Structured Audio. Proceedings of the ACM Conference on Computer Human Interaction, 9 pages.

51. Joseph Pear, Witold Kinsner and Deb Roy. (1987). Vocal shaping of retarded and autistic individuals using speech synthesis and speech recognition. Proceedings of the IEEE Conference of the Engineering in Medicine and Biology Society, pages 1787-1788.

 
Other Major Publications: Refereed Workshop Proceedings
 
52. Nick Mavridis and Deb Roy (2005). Grounded Situation Models for Robots: Bridging language, Perception, and Action. AAAI-05 Workshop on Modular Construction of Human-Like Intelligence.

53. Kai-yuh Hsiao, Peter Gorniak, and Deb Roy. (2005). NetP: A Network API for Building Heterogeneous Modular Intelligent Systems. Proc. AAAI 2005 Workshop in Modular Construction of Human-Like Intelligence.

54. Kai-yuh Hsiao and Deb Roy (2005). A Habit System for an Interactive Robot. Proceedings of the AAAI Fall Symposium 2005: From Reactive to Anticipatory Cognitive Embodied Systems.

55. Brian Whitman, Deb Roy and Barry Vercoe. (2003). Learning Word Meanings and Descriptive Parameter Spaces from Music. Proc. NAACL Workshop on Word Meaning.
 
56. Deb Roy, Kai-Yuh Hsiao and Nikolaos Mavridis. (2003). Conversational Robots: Building Blocks for Grounding Word Meaning. Proc. NAACL Workshop on Word Meaning.
 
57. Peter Gorniak and Deb Roy. (2003). Understanding Complex Visually Referring Utterances. NAACL Workshop on Word Meaning.
 
58. Deb Roy. (2001). Situation-Aware Spoken Language Processing. Royal Institute of Acoustics Workshop on Innovation in Speech Processing, Stratford-upon-Avon, England.
 
59. Fred Cummins and Deb Roy. (2001).Using Synchronous Speech to Minimize Variability. Royal Institute of Acoustics Workshop on Innovation in Speech Processing, Stratford-upon-Avon, England.
 
60. Deb Roy, Bernt Schiele, and Alex Pentland. (1999). Learning Audio-Visual Associations using Mutual Information. International Conference on Computer Vision, Workshop on Integrating Speech and Image Understanding.

**Comment by pbeshai** [comment]
We need to make sure all these titles are on the site:

Topic and time based media affinity estimation
DeepSpace: Mood-Based Image Texture Generation for Virtual Reality from Music
Rumor Gauge: Predicting the Veracity of Rumors on Twitter
SpeechBlocks: A Constructionist Early Literacy App
TweetVista: An AI-Powered Interactive Tool for Exploring Conversations on Twitter
Generating audience response metrics and ratings from social interest in time-based media
Dense home-based recordings reveal typical and atypical development of tense/aspect in a child with delayed language development
Generating Audience Response Metrics and Ratings from Social Interest In Time-Based Media
Estimating social interest in time-based media
Mapping Twitter Conversation Landscapes
TweetVista
Twitter Demographic Classification Using Deep Multi-modal Multi-task Learning
Estimating social interest in time-based media
Cross media targeted message synchronization
Tweet2vec: Learning tweet embeddings using character-level cnn-lstm encoder-decoder
Deepstance at semeval-2016 task 6: Detecting stance in tweets using character and word-level cnns
A Semi-Automatic Method for Efficient Detection of Stories on Social Media.
Automatic Detection and Categorization of Election-Related Tweets.
Tweet Acts: A Speech Act Classifier for Twitter.
Enhanced twitter sentiment classification using contextual information
Estimating social interest in time-based media
Human Atlas: A Tool for Mapping Social Networks
Tracking the Yak: An Empirical Study of Yik Yak.
Displaying estimated social interest in time-based media
Digital Stylometry: Linking Profiles Across Social Networks
Measuring Responsiveness in the Online Public Sphere for the 2016 US Election: Concepts
A human-machine collaborative system for identifying rumors on twitter
Predicting the birth of a spoken word
Topic and time based media affinity estimation
Cross media targeted message synchronization
Grounding language models in spatiotemporal context
Grounding verbs of motion in natural language commands to robots
Generating audience response metrics and ratings from social interest in time-based media
Displaying estimated social interest in time-based media
Generalized grounding graphs: A probabilistic framework for understanding grounded language
A portable audio/video recorder for longitudinal study of child development
Understanding Speech in Interactive Narratives with Crowdsourced Data.
Semi-automatic speech transcription
An automatic child-directed speech detector for the study of child language development
A longitudinal study of prosodic exaggeration in child-directed speech
Relating activity contexts to early word learning in dense longitudinal data
An Interface for Visualization and Exploration of Spatial Distributions.
Grounded Semantic Composition for Visual Scenes
Extracting aspects of determiner meaning from dialogue in a virtual world environment
Semi-automated dialogue act classification for situated social agents in games
Exploiting feature dynamics for active object recognition
Grounding spatial language for video search
An immersive system for browsing and visualizing surveillance video
Natural language command of an autonomous micro-air vehicle
Behavior Compilation for AI in Games.
Learning Meanings of Words and Constructions, Grounded in a Virtual Game.
Semi-automatic task recognition for interactive narratives with EAT &amp; RUN
Toward an interleaved model of actions and words in social simulation
Capturing and generating social behavior with the restaurant game
Toward understanding natural language directions
Assessing behavioral and computational approaches to naturalistic action segmentation
Contributions of prosodic and distributional features of caregivers' speech in early word learning
Automatic estimation of transcription accuracy and difficulty
Effects of caregiver prosody on child language acquisition
Grounding spatial prepositions for video search
Towards surveillance video search by natural language query
A human-machine collaborative approach to tracking human movement in multi-camera video
Automatic learning and generation of social behavior from collective human gameplay
Life in the network: the coming age of computational social science
Star Graphs: Discretization, visualization, and analysis of tracking data
Semantic context effects on color categorization
Fast transcription of unstructured audio recordings
Exploring word learning in a high-density longitudinal corpus
New horizons in the study of child language acquisition
Object schemas for grounding language in a responsive robot
Connecting Language to Robot Behaviour: An Architecture of Object Schemas
Grounded Language Modeling for Automatic Speech Recognition of Sports Video.
Object schemas for responsive robotic language use
The ITALK project: Integration and transfer of action and language knowledge in robots
A computational model of three facets of meaning
A mechanistic model of three facets of meaning
The restaurant game: Learning social behavior and language from thousands of players online
Totalrecall: visualization and semi-automatic annotation of very large audio-visual corpora.
A mechanistic model of three facets of meaning
Temporal feature induction for baseball highlight classification
Unsupervised content-based indexing of sports video
James H. Fowler
Interpretation of spatial language in a map navigation task
Situated models of meaning for sports video retrieval
Situated language understanding as filtering perceived affordances
Representing Intentions in a Cognitive Model of Language Acquisition: Effects of Phrase Structure on Situated Verb Learning.
A computational model of three facets of meaning
Grounding language in spatial routines
Mining temporal patterns of movement for video content classification
Grounded situation models for robots: Where words and percepts meet
Grounded situation models: Where words and percepts meet
The human speechome project
Modeling interactions from email communication
Spatial routines for a simulated speech-controlled vehicle
The Human Speechome Project
Learning from Observing Tutoring Collaboratively
Speech, space and purpose: Situated language understanding in computer games
Perceived affordances as a substrate for linguistic concepts
Learning influence among interacting Markov chains
Probabilistic grounding of situated speech using plan recognition and reference resolution
Gist icons: Seeing meaning in large bodies of literature
Connecting language to the world
Semiotic schemas: A framework for grounding language in action and perception
Grounding words in perception and action: computational insights
Grounded situation models for robots: Bridging language, perception, and action
Why verbs are harder to learn than nouns: Initial insights from a computational model of intention recognition in situated word learning
Intentional context in situated natural language learning
Speaking with your Sidekick: Understanding Situated Speech in Computer Role Playing Games.
Towards situated speech understanding: Visual context priming of language models
Effects of Category Labels on Induction and Visual Processing: Support or Interference?
Netp: A network API for building heterogeneous modular intelligent systems
Grounding language in the world: Schema theory meets semiotics
A habit system for an interactive robot
Visual memory augmentation: using eye gaze as an attention filter
Elvis: situated speech and gesture understanding for a robotic chandelier
10×—human-machine symbiosis
Affective learning—a manifesto
Mental imagery for a conversational robot
BISHOP| BLENDER: Spatially Grounded Language Understanding in 3D Modelling Software
Grounding language in the world: signs, schemas, and meaning
Beyond Linear Syntax: An Image-Oriented Communication Aid.
Grounded semantic composition for visual scenes
A visually grounded natural language interface for reference to spatial scenes
Augmenting user interfaces with adaptive speech commands
Coupling perception and simulation: Steps towards conversational robotics
Grounded spoken language acquisition: Experiments in word learning
Understanding complex visually referring utterances
Learning word meanings and descriptive parameter spaces from music
Conversational robots: building blocks for grounding word meaning
On Grounding the Content of Language
Robots, language, and meaning
A visual context-aware multimodal system for spoken language processing.
Visual context driven semantic priming of speech recognition and understanding
Ripley, Hand Me The Cup!(Sensorimotor representations for grounding word meaning)
Learning visually grounded words and syntax for a scene description task
Learning words from sights and sounds: A computational model
The ADS-to-IDS continuum: Developing an index for the study of infant directed speech prosody
A System that Learns to Describe Objects in Visual Scenes
Grounding natural spoken language semantics in visual perception and motor control
Towards visually-grounded spoken language acquisition
An adaptive context-sensitive communication aid
A trainable visually-grounded spoken language generation system
A trainable spoken language understanding system for visual object selection.
Situation-aware spoken language processing
Using synchronous speech to minimize variability
Grounded speech communication.
Learning Words from Sights and Sounds: A Computational
A computational model of word learning from multimodal sensory input
Learning from multimodal observations
Integration of speech and vision using mutual information
Learning visually grounded words and syntax of natural spoken language
Perceptual intelligence: learning gestures and words for individualized, adaptive interfaces
Learning audio-visual associations using mutual information
Learning from sights and sounds: a computational model
Learning words from natural audio-visual input.
Word learning in a multimodal environment
A phoneme probability display for individuals with hearing disabilities
Teachable interfaces for individuals with dysarthric speech and severe physical disabilities
Multimodal adaptive interfaces
Toco the toucan: a synthetic character guided by perception, emotion, and story.
Speaker identification based text to audio alignment for an audio retrieval system
Wearable audio computing: A survey of interaction techniques
Speaker indexing using neural network clustering of vowel spectra
Integration of a large text and audio corpus using speaker identification
Automatic spoken affect classification and analysis
NewsComm: a hand-held interface for interactive access to structured audio
Using acoustic structure in a hand-held audio playback device
NewsComm--a hand-held device for interactive access to structured audio
Computer assisted analysis of hand radiographs in infantile hypophosphatasia carriers
Interfaces programables para personas con disartria y grandes discapacidades físicas Teachable Interfaces for Individuals with Dysarthric Speech and Severe Physical Disabilities
See and Tell
Coupling Perception and Simulation: Steps Towards Conversational Robotics
Context-Aware Multimodal System For Spoken Language Processing
Coupling Robot Perception and Online Simulation for Grounding Conversational Semantics
Exploring SpeechBlocks: Piloting a Constructionist Literacy App with Preschool Children

**Comment by pbeshai** [comment]
@sgadgets I've gone through the list above and reduced it to the list that we do not already have in our publications data. We need to edit the publications file at `_data/publications.yml` to include all the missing publications.

When adding a publication, the procedure is roughly to go to the Google Scholar page and click to see if the paper is real/correctly matched. If so, create the citation in Deb's specified format, and for now, we can just copy the link to the PDF that google scholar has (see top right corner link after focusing on a paper, image below: )
![image](https://user-images.githubusercontent.com/793847/30818466-9dbf441c-a1e9-11e7-8035-a2fb48f69b1e.png)

We can use whatever that link is as the value for `pdf_file`. For example, this publication would be added as:

```yaml
- citation: |
    B. N. Chodirker, D. Roy, C. R. Greenberg, M. Cheang, J. A. Evans, & M. H. Reed. (1991). **Computer assisted analysis of hand radiographs in infantile hypophosphatasia carriers**. Pediatric Radiology, 21(3): 216-219.
  publication_year: 1991
  pdf_file: https://www.media.mit.edu/~dkroy/papers/pdf/chodirker_roy_1991.pdf
  academic: true
```

Note that I have been adding two asterisks (**) around titles to bold them in the output.

As a shortcut, before checking Google Scholar, check to see if Deb has already provided us a formatted citation in the list of examples above and use that. If it isn't there, there are ways to find the article on Google Scholar that will provide the citation for you.

**Comment by pbeshai** [comment]
Note that a few of these are patents. What should we do about them?

**Comment by pbeshai** [comment]
Ignoring patents for now.
